version: '3'
services:
 mysqldb:
    image: mysql
    container_name: mysql_prod
    command: mysqld --default-authentication-plugin=mysql_native_password
    volumes:
      - mysql-data:/var/local/mysql/data
    ports:
      - "3306:3306"
    hostname: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=examv2thouraya
    volumes:
      - db:/var/lib/mysql
 spring_app:
    image: azizkhoudi/repo:latest
    container_name: cntr_achat
    restart: on-failure
    ports:
        - 8089:8089
    environment:
        - spring.datasource.url=jdbc:mysql://mysqldb:3306/examv2thouraya?useSSL=false
    depends_on:
      - mysqldb
volumes:
  db:
